// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebarDocsId: [
    {
      type: "category",
      label: "FullStack Data AI",
      items: [
        "fullstack-data-ai/index",
        "fullstack-data-ai/artificial-intelligence",
        "fullstack-data-ai/machine-learning",
        "fullstack-data-ai/data-science",
        "fullstack-data-ai/data-engineering",
      ],
    },
    {
      type: "category",
      label: "Learning Roadmaps",
      items: [
        "roadmap/index",
        {
          type: "category",
          label: "Artificial Intelligence",
          items: ["roadmap/artificial-intelligence/index"],
        },
        {
          type: "category",
          label: "Machine Learning",
          items: ["roadmap/machine-learning/index"],
        },
        {
          type: "category",
          label: "Data Science",
          items: ["roadmap/data-science/index"],
        },
        {
          type: "category",
          label: "Data Engineering",
          items: ["roadmap/data-engineering/index"],
        },
      ],
    },
    { type: "autogenerated", dirName: "." },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
